# Generated by Django 3.1.4 on 2022-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_type', models.CharField(choices=[('sequence', 'Sequence')], max_length=15)),
                ('unit_type', models.CharField(choices=[('2', 'Single Units')], max_length=15)),
                ('standardize', models.BooleanField(blank=True, default=True, null=True)),
                ('length_of_trial', models.IntegerField(null=True)),
                ('bin_length', models.IntegerField(null=True)),
                ('split_chunks', models.CharField(blank=True, max_length=5000, null=True)),
                ('remove_low_baseline_clusters', models.BooleanField(blank=True, default=True, null=True)),
                ('remove_high_movement_correlation', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
