# Generated by Django 3.1.4 on 2021-03-14 19:36

import clustering.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('pca', 'PCA')], max_length=15)),
                ('algorithm_type', models.CharField(choices=[('gmm', 'Gaussian Mixture')], max_length=50)),
                ('nd', models.IntegerField(null=True)),
                ('histogram_data_files', models.FileField(null=True, upload_to=clustering.models.get_upload_path)),
                ('clusters_coordinates_files', models.FileField(null=True, upload_to=clustering.models.get_upload_path)),
                ('clustering_data_file', models.FileField(null=True, upload_to=clustering.models.get_upload_path)),
            ],
        ),
    ]
