# Generated by Django 3.1.4 on 2021-12-06 08:47

from django.db import migrations, models
import pl2kilosort.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_type', models.CharField(choices=[('sequence', 'Sequence')], max_length=15)),
                ('intensities_number', models.CharField(choices=[('7', '7'), ('10', '10')], max_length=10)),
                ('matlab_files', models.FileField(null=True, upload_to=pl2kilosort.models.get_upload_path)),
                ('plexon_files', models.FileField(null=True, upload_to=pl2kilosort.models.get_upload_path)),
            ],
        ),
    ]
